INSERT INTO subject (title, facultyTitle, description) VALUES ('AADMS', 'ART', 'Arts Administration Specialization Seminar');
INSERT INTO subject (title, facultyTitle, description) VALUES ('AB', 'VPA', 'Arabic (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ACC', 'ART', 'Accounting');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ACINTY', 'VPA', 'Academic Integrity');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ACTSC', 'MAT', 'Actuarial Science');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ADMGT', 'ENG', 'Advanced Management');
INSERT INTO subject (title, facultyTitle, description) VALUES ('AES', 'ENV', 'Applied Environmental Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('AFM', 'ART', 'Accounting and Financial Managment');
INSERT INTO subject (title, facultyTitle, description) VALUES ('AHS', 'AHS', 'Applied Health Sciences');
INSERT INTO subject (title, facultyTitle, description) VALUES ('AMATH', 'MAT', 'Applied Mathematics');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ANTH', 'ART', 'Anthropology');
INSERT INTO subject (title, facultyTitle, description) VALUES ('APHYS', 'ENG', 'Applied Physics');
INSERT INTO subject (title, facultyTitle, description) VALUES ('APPLS', 'REN', 'Applied Language Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ARBUS', 'ART', 'Arts and Business');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ARCH', 'ENG', 'Architecture');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ARCHL', 'VPA', 'Archeology (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ART', 'ART', 'Art');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ARTS', 'ART', 'Arts');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ASIAN', 'REN', 'Asian Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ASTRN', 'VPA', 'Astronomy (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('AVIA', 'VPA', 'Aviation');
INSERT INTO subject (title, facultyTitle, description) VALUES ('BASE', 'REN', 'Bridge to Academic Success in English');
INSERT INTO subject (title, facultyTitle, description) VALUES ('BE', 'ENG', 'Business Entrepreneurship');
INSERT INTO subject (title, facultyTitle, description) VALUES ('BET', 'ENG', 'Business, Entrepreneurship and Technology');
INSERT INTO subject (title, facultyTitle, description) VALUES ('BIOL', 'SCI', 'Biology');
INSERT INTO subject (title, facultyTitle, description) VALUES ('BME', 'ENG', 'Biomedical Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('BOT', 'VPA', 'Botany (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('BUS', 'MAT', 'Business');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CCIV', 'ART', 'Classical Civilization');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CDNST', 'STP', 'Canadian Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CEDEV', 'VPA', 'Children''s Education & Development (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CHE', 'ENG', 'Chemical Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CHEM', 'SCI', 'Chemistry');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CHINA', 'REN', 'Chinese');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CIVE', 'ENG', 'Civil Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CLAS', 'ART', 'Classical Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CM', 'MAT', 'Computational Mathematics');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CMW', 'CGC', 'Church Music and Worship');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CO', 'MAT', 'Combinatorics and Optimization');
INSERT INTO subject (title, facultyTitle, description) VALUES ('COGSCI', 'ART', 'Cognitive Science');
INSERT INTO subject (title, facultyTitle, description) VALUES ('COMM', 'MAT', 'Commerce');
INSERT INTO subject (title, facultyTitle, description) VALUES ('COMPT', 'VPA', 'Computing (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('COMST', 'VPA', 'Communication Studies (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CONST', 'VPA', 'Contemporary Studies (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('COOP', 'VPA', 'Co-op');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CROAT', 'ART', 'Croatian');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CS', 'MAT', 'Computer Science');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CT', 'STJ', 'Catholic Thought');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CULMG', 'ART', 'Cultural Management');
INSERT INTO subject (title, facultyTitle, description) VALUES ('CULT', 'VPA', 'Cultural Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('DAC', 'ART', 'Digital Arts Communication');
INSERT INTO subject (title, facultyTitle, description) VALUES ('DANCE', 'ART', 'Dance');
INSERT INTO subject (title, facultyTitle, description) VALUES ('DEI', 'ART', 'Digital Experience Innovation');
INSERT INTO subject (title, facultyTitle, description) VALUES ('DES', 'ENG', 'Design');
INSERT INTO subject (title, facultyTitle, description) VALUES ('DEVIS', 'VPA', 'Development & International Studies (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('DM', 'ENG', 'Design and Manufacturing');
INSERT INTO subject (title, facultyTitle, description) VALUES ('DRAMA', 'ART', 'Drama');
INSERT INTO subject (title, facultyTitle, description) VALUES ('DUTCH', 'ART', 'Dutch');
INSERT INTO subject (title, facultyTitle, description) VALUES ('EARTH', 'SCI', 'Earth Science');
INSERT INTO subject (title, facultyTitle, description) VALUES ('EASIA', 'REN', 'East Asian Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('EBUS', 'ENV', 'Environment and Business');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ECE', 'ENG', 'Electrical and Computer Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ECON', 'ART', 'Economics');
INSERT INTO subject (title, facultyTitle, description) VALUES ('EFAS', 'REN', 'English for Academic Success');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ELE', 'ENG', 'Electrical Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ELPE', 'VPA', 'English Language Proficiency Examination');
INSERT INTO subject (title, facultyTitle, description) VALUES ('EMLS', 'REN', 'English for Multilingual Speakers');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ENBUS', 'ENV', 'Environment and Business');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ENGL', 'ART', 'English');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ENVE', 'ENG', 'Environmental Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ENVS', 'ENV', 'Environmental Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ERS', 'ENV', 'Environment and Resource Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ESL', 'REN', 'English as a Second Language');
INSERT INTO subject (title, facultyTitle, description) VALUES ('EVSY', 'VPA', 'Environment and Society');
INSERT INTO subject (title, facultyTitle, description) VALUES ('FILM', 'VPA', 'Film (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('FINAN', 'ART', 'Finance');
INSERT INTO subject (title, facultyTitle, description) VALUES ('FINE', 'ART', 'Fine Arts');
INSERT INTO subject (title, facultyTitle, description) VALUES ('FR', 'ART', 'French Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('FRCS', 'ART', 'French Cultural Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GBDA', 'ART', 'Global Business and Digital Arts');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GEMCC', 'ENV', 'Geography and Environmental Mgmt, Climate Change');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GENE', 'ENG', 'General Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GEOE', 'ENG', 'Geological Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GEOG', 'ENV', 'Geography');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GEOL', 'VPA', 'Geology (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GER', 'ART', 'German');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GERON', 'AHS', 'Gerontology');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GGOV', 'ART', 'Global Governance');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GLOBAL', 'VPA', 'Global Studies (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GRAD', 'GRAD', 'Continuing Graduate Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GRK', 'ART', 'Greek');
INSERT INTO subject (title, facultyTitle, description) VALUES ('GS', 'GRAD', 'Graduate Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('HEBRW', 'VPA', 'Hebrew (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('HIST', 'ART', 'History');
INSERT INTO subject (title, facultyTitle, description) VALUES ('HLTH', 'AHS', 'Health Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('HRCS', 'ART', 'Human Relations & Counselling Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('HRM', 'ART', 'Human Resources Management');
INSERT INTO subject (title, facultyTitle, description) VALUES ('HS', 'VPA', 'High School');
INSERT INTO subject (title, facultyTitle, description) VALUES ('HSG', 'AHS', 'Health Studies and Gerontology');
INSERT INTO subject (title, facultyTitle, description) VALUES ('HUMSC', 'STJ', 'Human Sciences');
INSERT INTO subject (title, facultyTitle, description) VALUES ('HUNGN', 'ART', 'Hungarian');
INSERT INTO subject (title, facultyTitle, description) VALUES ('IFS', 'ART', 'Inter-Faculty Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('INDEV', 'ENV', 'International Development');
INSERT INTO subject (title, facultyTitle, description) VALUES ('INTEG', 'ENV', 'Integrated Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('INTERN', 'VPA', 'Internship');
INSERT INTO subject (title, facultyTitle, description) VALUES ('INTST', 'ART', 'International Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('INTTS', 'ART', 'International Trade Seminars');
INSERT INTO subject (title, facultyTitle, description) VALUES ('IS', 'IS', 'Independent Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ISS', 'REN', 'Interdisciplinary Social Sciences');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ITAL', 'STJ', 'Italian');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ITALST', 'STJ', 'Italian Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('JAPAN', 'REN', 'Japanese');
INSERT INTO subject (title, facultyTitle, description) VALUES ('JS', 'ART', 'Jewish Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('KIN', 'AHS', 'Kinesiology');
INSERT INTO subject (title, facultyTitle, description) VALUES ('KOREA', 'REN', 'Korean');
INSERT INTO subject (title, facultyTitle, description) VALUES ('KPE', 'VPA', 'Kinesiology and Physical Education (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('LANG', 'VPA', 'Language (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('LAT', 'ART', 'Latin');
INSERT INTO subject (title, facultyTitle, description) VALUES ('LATAM', 'ART', 'Latin American Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('LED', 'ENV', 'Local Economic Development');
INSERT INTO subject (title, facultyTitle, description) VALUES ('LS', 'ART', 'Legal Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('LSC', 'ART', 'Legal Studies and Criminology');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MATBUS', 'MAT', 'Mathematical Business');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MATH', 'MAT', 'Mathematics');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ME', 'ENG', 'Mechanical Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MEDST', 'VPA', 'Media Studies (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MEDVL', 'ART', 'Medieval Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MENV', 'ENV', 'Man Environment');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MES', 'ART', 'Middle Eastern Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MI', 'VPA', 'Mediterranean Studies (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MISC', 'VPA', 'Miscellaneous');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MNS', 'SCI', 'Materials and Nano-Sciences');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MSCI', 'ENG', 'Management Sciences');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MSE', 'ENG', 'Management & Systems');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MTE', 'ENG', 'Mechatronics Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MTHEL', 'MAT', 'Mathematics Elective');
INSERT INTO subject (title, facultyTitle, description) VALUES ('MUSIC', 'CGC', 'Music');
INSERT INTO subject (title, facultyTitle, description) VALUES ('NANO', 'GRAD', 'Nanotechnology');
INSERT INTO subject (title, facultyTitle, description) VALUES ('NATST', 'STP', 'Native Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('NE', 'ENG', 'Nanotechnology Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('NES', 'VPA', 'Near Eastern Studies (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('OPTOM', 'SCI', 'Optometry');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PACS', 'CGC', 'Peace and Conflict Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PAS', 'ART', 'Personnel & Administration Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PD', 'VPA', 'Professional Development');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PDARCH', 'ENG', 'Professional Development for Architecture Students');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PDENG', 'ENG', 'Professional Development for Engineering Students');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PDPHRM', 'SCI', 'Professional Development for Pharmacy Students');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PED', 'VPA', 'Physical Education (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PERST', 'ART', 'Personnel Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PHARM', 'SCI', 'Pharmacy');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PHIL', 'ART', 'Philosophy');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PHS', 'AHS', 'Public Health Sciences');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PHYS', 'SCI', 'Physics');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PLAN', 'ENV', 'Planning');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PMATH', 'MAT', 'Pure Mathematics');
INSERT INTO subject (title, facultyTitle, description) VALUES ('POLSH', 'ART', 'Polish');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PORT', 'ART', 'Portuguese');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PS', 'ART', 'Public Serivce');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PSCI', 'ART', 'Political Science');
INSERT INTO subject (title, facultyTitle, description) VALUES ('PSYCH', 'ART', 'Psychology');
INSERT INTO subject (title, facultyTitle, description) VALUES ('QIC', 'GRAD', 'Quantum Information and Computation');
INSERT INTO subject (title, facultyTitle, description) VALUES ('REC', 'AHS', 'Recreation and Leisure Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('REES', 'ART', 'Russian and Eastern European Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('RELC', 'VPA', 'Religion & Culture (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('RS', 'ART', 'Religious Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('RSCH', 'VPA', 'Research');
INSERT INTO subject (title, facultyTitle, description) VALUES ('RUSS', 'ART', 'Russian');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SCBUS', 'SCI', 'Science and Business');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SCI', 'SCI', 'Science');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SDS', 'REN', 'Social Development Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SE', 'VPA', 'Software Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SEQ', 'MAT', 'Co-op Sequence');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SI', 'REN', 'Studies in Islam');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SIPAR', 'STP', 'Studies in Personality & Religion');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SMF', 'STJ', 'Sexuality, Marriage and the Family');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SOC', 'ART', 'Sociology');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SOCIN', 'ENV', 'Social Innovation');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SOCWK', 'REN', 'Social Work (Social Development Studies)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SOCWL', 'VPA', 'Social Welfare (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SPAN', 'ART', 'Spanish');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SPCOM', 'ART', 'Speech Communication');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SPD', 'STP', 'Spirituality and Personal Development');
INSERT INTO subject (title, facultyTitle, description) VALUES ('STAT', 'MAT', 'Statistics');
INSERT INTO subject (title, facultyTitle, description) VALUES ('STV', 'ENG', 'Society, Technology and Values');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SUSM', 'ENV', 'Sustainability Management');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SWK', 'AHS', 'Social Work');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SWREN', 'REN', 'Social Work (Bachelor of Social Work)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('SYDE', 'ENG', 'Systems Design Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('TAX', 'ART', 'Taxation');
INSERT INTO subject (title, facultyTitle, description) VALUES ('THTRE', 'VPA', 'Theatre (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('TN', 'GRAD', 'Theoretical Neuroscience');
INSERT INTO subject (title, facultyTitle, description) VALUES ('TOUR', 'ENV', 'Tourism');
INSERT INTO subject (title, facultyTitle, description) VALUES ('TPM', 'ENG', 'Technical Presentation Milestone');
INSERT INTO subject (title, facultyTitle, description) VALUES ('TPPE', 'ENG', 'Technical Presentation Proficiency Requirement');
INSERT INTO subject (title, facultyTitle, description) VALUES ('TS', 'CGC', 'Theological Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('UKRAN', 'ART', 'Ukrainian');
INSERT INTO subject (title, facultyTitle, description) VALUES ('UN', 'ENG', 'Nuclear Engineering');
INSERT INTO subject (title, facultyTitle, description) VALUES ('UNIV', 'VPA', 'University');
INSERT INTO subject (title, facultyTitle, description) VALUES ('URBAN', 'VPA', 'Urban Studies (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('UU', 'VPA', 'University Interdisciplinary Studies (WLU)');
INSERT INTO subject (title, facultyTitle, description) VALUES ('VCULT', 'ART', 'Visual Culture');
INSERT INTO subject (title, facultyTitle, description) VALUES ('WATER', 'GRAD', 'Water');
INSERT INTO subject (title, facultyTitle, description) VALUES ('WHMIS', 'SCI', 'Workplace Hazardous Materials Information Systems');
INSERT INTO subject (title, facultyTitle, description) VALUES ('WKRPT', 'VPA', 'Work-term Report');
INSERT INTO subject (title, facultyTitle, description) VALUES ('WS', 'ART', 'Women''s Studies');
INSERT INTO subject (title, facultyTitle, description) VALUES ('ZOOL', 'VPA', 'Zoology (WLU)');
