INSERT INTO faculty (title, shortName, fullName) VALUES ('AHS', 'Applied Health Sciences', 'Faculty of Applied Health Sciences');
INSERT INTO faculty (title, shortName, fullName) VALUES ('ART', 'Arts', 'Faculty of Arts');
INSERT INTO faculty (title, shortName, fullName) VALUES ('CGC', 'Conrad Grebel', 'Conrad Grebel University College');
INSERT INTO faculty (title, shortName, fullName) VALUES ('ENG', 'Engineering', 'Faculty of Engineering');
INSERT INTO faculty (title, shortName, fullName) VALUES ('ENV', 'Environment', 'Faculty of Environment');
INSERT INTO faculty (title, shortName, fullName) VALUES ('GRAD', 'Graduate Studies', 'Graduate Studies');
INSERT INTO faculty (title, shortName, fullName) VALUES ('IS', 'Independent Studies', 'Independent Studies');
INSERT INTO faculty (title, shortName, fullName) VALUES ('MAT', 'Mathematics', 'Faculty of Mathematics');
INSERT INTO faculty (title, shortName, fullName) VALUES ('REN', 'Renison', 'Renison University College');
INSERT INTO faculty (title, shortName, fullName) VALUES ('SCI', 'Science', 'Faculty of Science');
INSERT INTO faculty (title, shortName, fullName) VALUES ('STJ', 'St. Jeromes', 'St. Jerome''s University');
INSERT INTO faculty (title, shortName, fullName) VALUES ('STP', 'St. Pauls', 'St. Paul''s University College');
INSERT INTO faculty (title, shortName, fullName) VALUES ('THL', 'Theology', 'Theology');
INSERT INTO faculty (title, shortName, fullName) VALUES ('VPA', 'Interdisciplinary', 'Interdisciplinary Studies');
